local L = Cornucopia.Locals
if GetLocale() ~= 'ptBR' then return end

L['CannotConfig'] = 'Não pode configurar a interface enquanto estiver em combate!'
L['Add'] = 'Nova Barra'
L['Back'] = 'Enviar para Trás'
L['Front'] = 'Trazer para a Frente'
L['BottomLeft'] = 'Inf.Esquerdo'
L['BottomRight'] = 'Inf.Direito'
L['TopLeft'] = 'Sup.Esquerdo'
L['TopRight'] = 'Sup.Direito'
L['Metrics'] = 'Metricas'

L['BinderTip'] = 'Passe o mouse por cima de um botão e pressione uma tecla para definir a tecla de atalho.|nA tecla "Esc" remove o atalho.'
L['MinimapButtonDesc'] = 'Se não quiser usar o botão|ndo minimapa para entrar nas configurações,|npode sempre definir uma tecla de atalho para isso.'
L['RulersDesc'] = 'Pode segurar a tecla "Alt" para|nativar/desativar as réguas.'

L["EventsDesc"] = "Estas opções permitem-no fazer com que as ações na sua barra |cffffffffse alterem|r depenendo da |cffffffffsituação|r em que se encontra."
L["IDsDesc"] = "Infelizmente, o cliente do jogo apenas lhe permite ter até |cffffffff120 ações diferentes|r.|n|nO número de ações que você gasta aumenta com o número de |cffffffffbotões|r que usar e os |cffffffffeventos|r que ativar."

L["StanceDesc"] =  "Quando ativado, as ações nesta barra irão mudar quando entrar em |cffffffff%s|r."
L["CombatStancesDesc"] = "Quando ativado, as ações nesta barra irão mudar dependendo da sua |cffffffffPostura de Combate."
L["ShapeshiftingDesc"] = "Quando ativado, as ações nesta barra irão mudar dependendo da sua |cffffffffForma Animal."
L["TalentFormsDesc"] = "Quando ativado, as ações nesta barra irão mudar quando entrar na forma de |cffffffffLuniscante|r ou |cffffffffÁrvore da Vida|r."
L["StealthDesc"] = "Quando ativado, as ações nesta barra irão mudar quando entrar em |cffffffff%s|r."
L["TalentForms"] = "Formas de Talentos"

L["FriendlyDesc"] = "Quando ativado, as ações nesta barra irão mudar quando selecionar um |cffffffffjogador ou monstro aliado|r.\n\nÚtil para colocar bônus e habilidades de cura!"
L["KeyDesc"] = "Quando ativado, as ações nesta barra irão mudar quando segurar a tecla |cffffffff%s|r no seu teclado."
L["CombatDesc"] = "Quando ativado, as ações nesta barra irão mudar dependendo de você estar em |cffffffffcombate|r ou não."
L["GroupDesc"] = "Quando ativado, as ações nesta barra irão mudar dependendo de você estar em um |cffffffffgrupo|r ou não."
L["VehicleDesc"] = "Quando ativado, esta barra de ação irá mostrar as |cffffffffHabilidades do Veículo|r quando entrar em um."

L['Flip'] = 'Inverter'
L["Right"] = "Direito"
L["Screen"] = "Tela"
L["Rulers"] = "Réguas"
L["Help"] = "Ajuda"
L["End"] = "Final"
L["Theme"] = "Tema"
L["Minimap Button"] = "Botão do Minimapa"
L["Type"] = "Tipo"
L["Bottom"] = "Inferior"
L["Reputation"] = "Reputação"
L["Start From"] = "Começar do Canto"
L["Top"] = "Superior"
L["Are you sure you want to delete all the selected bars?"] = "Tem a certeza que quer eliminar todas as barras selecionadas?"
L["Action Buttons"] = "Botões de Ação"
L["Grow From"] = "Crescer do Canto"
L["Special Actions"] = "Ações Especiais"
L["Debuffs"] = "Penalidades"
L["Zone"] = "Zona"
L["Color"] = "Cor"
L["Durability & Vehicle Seats"] = "Durabilidade e Lugares do Veículo"
L["Anchor"] = "Fixar à"
L["Translucent"] = "Translúcido"
L["Size"] = "Tamanho"
L["Options"] = "Opções"
L["Layout"] = "Disposição"
L["Experience"] = "Experiência"
L["Height"] = "Altura"
L["Buffs"] = "Bônus" 
L["Objectives"] = "Objetivos"
L["Combat"] = "Combate"
L["Group"] = "Grupo"
L["Rows"] = "Linhas"
L["Left"] = "Esquerdo"
L["Capture Timers"] = "Cronômetros de Captura"
L["Crop"] = "Cortar"
L["Hide Macro Names"] = "Esconder Nomes dos Macros"
L["Spacing"] = "Espaçamento"
L["Friendly Target"] = "Alvo Aliado"
L["Columns"] = "Colunas"
L["Hide Bindings"] = "Esconder Atalhos"
L["Width"] = "Largura"
L["Events"] = "Eventos"
L["Leave Vehicle"] = "Sair do veículo"
L["Center"] = "Centro"
L["Opaque"] = "Opaco"
L["Start"] = "Começar"
L["With"] = "Com o Canto"
L["Constrain Porportional"] = "Manter as proporções"
L["Bags"] = "Bolsas"
L["Extra Action"] = "Ação Extra"
L["Instance"] = "Instâncias"
L["Minimap"] = "Minimapa"
L["Opacity"] = "Opacidade"
L["Vehicle & Possess"] = "Veículos"
L["Pet Control"] = "Controlo do Ajudante"
L["Art"] = "Arte"
L["Background"] = "Plano de Fundo"
L["File"] = "Ficheiro"
L["Shape"] = "Forma"
L["To"] = "Ao"